[[icedos.repositories]]
url = "github:icedos/providers"
# overrideUrl = "path:/home/ice/Projects/icedos/providers"

[icedos.users.ice]
description = "IceDBorn"

[icedos.system]
packages = [
  "eden",
  "pcsx2",
  "signal-desktop",
  "spotube",
  "wl-freeze",
]
ssh = true
version = "25.11"

[icedos.system.build-vm]
cores = 6
memory = 8192

[icedos.system.cache]
enable = true
pinInputs = true

[icedos.system.git.users.ice]
username = "IceDBorn"
email = "git.outsider841@simplelogin.fr"
