[[icedos.repositories]]
url = "github:icedos/mcp-server"
# overrideUrl = "path:/home/ice/Projects/icedos/mcp-server"

[icedos.users.ice]
description = "IceDBorn"

[icedos.system]
packages = [
  "android-studio",
  "faugus-launcher",
  "shadps4",
  "shadps4-qtlauncher",
  "signal-desktop",
  "spotube",
]
ssh = true
version = "25.11"

[icedos.system.buildVm]
cores = 6
memory = 8192

[icedos.system.git.users.ice]
username = "IceDBorn"
email = "git.outsider841@simplelogin.fr"
