[[icedos.repositories]]
url = "github:icedos/apps"
modules = [
  "me3",
  "reigntweak",
]

[icedos.applications.me3.games.nightreign]
profileVersion = "v1"
disable_arxan = true
start_online = true
natives = [
  { name = "cl-server-redirector", path = "/mnt/games-ssd/games/nr/packages/variations/output/dll/ServerRedirector/cl_server_redirector.dll", load_early = true },
  { name = "custom_drop_fxrs", path = "/mnt/games-ssd/games/nr/packages/variations/output/dll/custom_drop_fxrs.dll", load_early = true },
  { name = "disable-chromatic-aberration", path = "/mnt/games-ssd/games/nr/natives/disable-chromatic-aberration.dll" },
  { name = "disable-sharpening", path = "/mnt/games-ssd/games/nr/natives/disable-sharpening.dll" },
  { name = "disable-vignette", path = "/mnt/games-ssd/games/nr/natives/disable-vignette.dll" },
  { name = "nrallinone", path = "/mnt/games-ssd/games/nr/packages/variations/output/dll/target/release/nrallinone.dll", load_early = true },
  { name = "seamless-coop", path = "/mnt/games-ssd/games/nr/natives/nrsc.dll", load_early = true },
  { name = "storm-control", path = "/mnt/games-ssd/games/nr/natives/storm-control.dll", load_early = true },
  { name = "timer", path = "/mnt/games-ssd/games/nr/natives/timer.dll" },
  { name = "ultrawide", path = "/mnt/games-ssd/games/nr/natives/ultrawide.dll" },
  { name = "unlock-fps", path = "/mnt/games-ssd/games/nr/natives/unlock-fps.dll" },
  { name = "unlock_wwise_states_nr", path = "/mnt/games-ssd/games/nr/packages/variations/output/dll/unlock_wwise_states_nr.dll", load_early = true },
]
packages = [
  { id = "blue-filter-removal", path = "/mnt/games-ssd/games/nr/packages/blue-filter-removal" },
  { id = "variations", path = "/mnt/games-ssd/games/nr/packages/variations/output" },
]

[[icedos.applications.me3.games.nightreign.profiles]]
name = "nr"
natives = [
  "cl-server-redirector",
  "disable-chromatic-aberration",
  "disable-sharpening",
  "disable-vignette",
  # "seamless-coop",
  "timer",
  "ultrawide",
  "unlock-fps",
]
packages = [
  "blue-filter-removal",
]

[[icedos.applications.me3.games.nightreign.profiles]]
name = "nr-storm-control"
dependencies = ["nr"]
natives = ["storm-control"]

[[icedos.applications.me3.games.nightreign.profiles]]
name = "nr-variations"
dependencies = ["nr-storm-control"]
packages = ["variations"]
natives = [
  "custom_drop_fxrs",
  "nrallinone",
  "unlock_wwise_states_nr"
]
