[[icedos.repositories]]
url = "github:icedos/apps"
modules = [
  "me3",
  "reigntweak",
]

[icedos.applications.me3.games.nightreign]
profileVersion = "v1"
disable_arxan = true
start_online = true
natives = [
  { name = "affinity-fix", path = "/mnt/games-ssd/games/nr/packages/variations/output/dll/NightreignAffinityFix.dll", load_early = true },
  { name = "cl-server-redirector", path = "/mnt/games-ssd/games/nr/packages/variations/output/dll/ServerRedirector/cl_server_redirector.dll", load_early = true },
  { name = "chance-setter", path = "/mnt/games-ssd/games/nr/packages/variations/output/dll/ChanceSetterLoader.dll" },
  { name = "custom_drop_fxrs", path = "/mnt/games-ssd/games/nr/packages/variations/output/dll/custom_drop_fxrs.dll", load_early = true },
  { name = "disable-chromatic-aberration", path = "/mnt/games-ssd/games/nr/packages/variations/output/dll/DisableChromaticAberration.dll", load_early = true },
  { name = "disable-sharpening", path = "/mnt/games-ssd/games/nr/packages/variations/output/dll/DisableSharpening.dll" },
  { name = "disable-vignette", path = "/mnt/games-ssd/games/nr/packages/variations/output/dll/DisableVignette.dll", load_early = true },
  { name = "helen-mimic", path = "/mnt/games-ssd/games/nr/packages/variations/output/dll/HelenMimic.dll", load_early = true },
  { name = "nrallinone", path = "/mnt/games-ssd/games/nr/packages/variations/output/dll/target/release/nrallinone.dll", load_early = true },
  { name = "timer", path = "/mnt/games-ssd/games/nr/packages/variations/output/dll/StormTimer.dll" },
  { name = "ultrawide", path = "/mnt/games-ssd/games/nr/packages/variations/output/dll/UltrawideFix.dll" },
  { name = "unlock-fps", path = "/mnt/games-ssd/games/nr/packages/variations/output/dll/UnlockTheFps.dll" },
  { name = "unlock_wwise_states_nr", path = "/mnt/games-ssd/games/nr/packages/variations/output/dll/unlock_wwise_states_nr.dll", load_early = true },
]
packages = [
  { id = "variations", path = "/mnt/games-ssd/games/nr/packages/variations/output" },
]

[[icedos.applications.me3.games.nightreign.profiles]]
name = "nr"
natives = [
  "affinity-fix",
  "cl-server-redirector",
  "disable-chromatic-aberration",
  "disable-sharpening",
  "disable-vignette",
  "timer",
  "ultrawide",
  "unlock-fps",
]

[[icedos.applications.me3.games.nightreign.profiles]]
name = "nr-variations"
dependencies = ["nr"]
packages = ["variations"]
natives = [
  "chance-setter",
  "custom_drop_fxrs",
  "helen-mimic",
  "nrallinone",
  "unlock_wwise_states_nr"
]
