[[icedos.repositories]]
url = "github:icedos/desktop"
# overrideUrl = "path:/home/ice/.code/icedos/desktop"

[icedos.desktop]
autologinUser = "ice"
defaultBrowser = "helium.desktop"
defaultEditor = "dev.zed.Zed.desktop"
wallpaper = "/home/ice/Pictures/wallpaper.jpg"

[icedos.desktop.bookmarks]
public = false
templates = false

[icedos.desktop.windows.focus]
delay = 0
followsMouse = true

[icedos.desktop.xdg-desktop-portal]
forceGtkFilePicker = true

[icedos.desktop.stylix]
disabledTargets = ["console", "kmscon", "zed"]

[icedos.desktop.windows]
maximizeButton = false
minimizeButton = false

[icedos.desktop.users.ice]
startupScript = "helium-social"
