[[icedos.repositories]]
url = "github:icedos/hardware"
# overrideUrl = "path:/home/ice/Projects/icedos/hardware"
modules = [
  "bluetooth",
  "cachyos-kernel",
  "disable-ipv6",
  "kernel",
  "openrgb",
  "pipewire",
  "radeon",
  "ryzen",
  "samba",
  "scx",
  "uinput",
  "upower",
  "wake-on-lan",
  "xpadneo",
  "zenergy",
]

[icedos.hardware]
swapDevices = ["/swap/swapfile"]

[icedos.hardware.bluetooth]
controllerMode = "dual"

[icedos.system.bootloaders.systemd-boot]
mountPoint = "/boot"

[icedos.hardware.graphics.radeon]
featureMask = "0xffffffff"

[icedos.hardware.kernel]
variant = "latest-lto-x86_64-v3"

[icedos.hardware.kernel.scx]
extraArgs = ["--performance"]

[icedos.hardware.graphics.mesa]
git = true

[icedos.hardware.network]
firewall = false

[[icedos.hardware.network.samba.shares]]
forceUser = "ice"
guestOk = true
name = "Nvidia Shield Videos"
path = "/mnt/docker-ssd/videos/shield"
readOnly = true

[icedos.hardware.network.wakeOnLan]
interfaces = ["enp9s0"]

[icedos.hardware.pipewire.echoCancellation]
enable = true

[icedos.hardware.pipewire.noiseCancellation]
enable = true
