[[icedos.repositories]]
url = "github:icedos/hardware"
# overrideUrl = "path:/home/ice/.code/icedos/hardware"
modules = [
  "disable-ipv6",
  "kernel",
  "radeon",
  "ryzen",
]

[icedos.hardware.kernel]
variant = "latest"

[icedos.hardware.network]
firewall = false
