[icedos.applications.sunshine]
capSysAdmin = true

[icedos.applications.sunshine.settings]
capture = "kms"
sunshine_name = "Saloni Desktop"

[icedos.applications.steam.headless-session]
excludeHostControllers = false
name = "Saloni City"
