[icedos.applications.zed]
vim = true

[icedos.applications.zed.copySelectionLocation]
enable = true

[icedos.applications.zed.font]
size = 12

[icedos.applications.zed.lsp.taplo.settings.formatter]
alignComments = false
reorderKeys = false
